### PR TITLE
Local of Google Closure Compiler support.

### PR DESCRIPTION
**Pull request by VAllens**
Use to the IKVM.
Compile compiler.jar for compiler.dll
JDK is no longer required.
Updated Use dotLess 1.4.1.0, AjaxMin 5.11.5295.12309 and Log4Net 2.0.3
Updated Build folder

### CODE REVIEW

**Comment by buunguyen** [comment]
Sorry for taking forever on this. Quick question: did you self-build compiler.dll or does it come from somewhere?

**Comment by VAllens** [comment]
Hi,buunguyen.
Through the IKVM.NET to convert the compiler.jar to compiler.dll.
The compiler.jar from https://github.com/google/closure-compiler

**Comment by buunguyen** [comment]
Very interesting. I'm not familiar with IKMV.NET (and certainly the resulting Closure compiler.dll). Do you know if there's indeed a performance benefit of doing this? I understand it's more convenient as one doesn't have to setup the JVM, but I think in this case, performance triumphs other considerations.

**Comment by VAllens** [comment]
Hi,buunguyen.
Performance is not much difference, I just don't want to install the Java virtual machine.
Oh, I just remembered. Microsoft AjaxMin recently released version, compressed size and slightly better than the Google Closure Compiler.

**Comment by buunguyen** [comment]
Yeah, I use the latest version in 2.3.0.4. Probably I should make it the default in the next version.

**Comment by VAllens** [comment]
Oh, very good.

**Comment by VAllens** [comment]
I think it should be changed to DLL, do not use jar.
I suggest you consider.

**Pull request closed without merging**
